import { App, normalizePath, TFile, TFolder } from 'obsidian';
import type { TodoPluginSettings } from './settings';

const TODO_PATTERN = /^\s*- \[ \] 202\d.*$/;

interface TodoMatch {
	line: string;
	sourcePath: string;
}

export async function refreshTodoIndex(
	app: App,
	settings: TodoPluginSettings,
): Promise<number> {
	const scanFolders = normalizeScanFolders(settings.scanFolders);
	const outputFile = normalizeOutputFile(settings.outputFile);
	const tasks = await collectTodos(app, scanFolders, outputFile);
	const content = renderTodoIndex(tasks);

	await writeOutputFile(app, outputFile, content);

	return tasks.length;
}

async function collectTodos(
	app: App,
	scanFolders: string[],
	outputFile: string,
): Promise<TodoMatch[]> {
	const tasks: TodoMatch[] = [];

	for (const file of app.vault.getMarkdownFiles()) {
		if (file.path === outputFile || !isInScanFolder(file.path, scanFolders)) {
			continue;
		}

		const content = await app.vault.cachedRead(file);
		for (const line of content.split(/\r?\n/)) {
			if (TODO_PATTERN.test(line)) {
				tasks.push({
					line: line.trimStart(),
					sourcePath: file.path,
				});
			}
		}
	}

	return tasks;
}

function renderTodoIndex(tasks: TodoMatch[]): string {
	const lines = [
		'# TODO',
		'',
		'Generated by Todo Plugin. Do not edit this file manually.',
		'',
	];

	if (tasks.length === 0) {
		lines.push('No matching todos found.');
	} else {
		for (const task of tasks) {
			const linkTarget = task.sourcePath.replace(/\.md$/i, '');
			lines.push(`${task.line} ([[${linkTarget}|${task.sourcePath}]])`);
		}
	}

	return `${lines.join('\n')}\n`;
}

async function writeOutputFile(
	app: App,
	outputFile: string,
	content: string,
): Promise<void> {
	const existing = app.vault.getAbstractFileByPath(outputFile);

	if (existing instanceof TFile) {
		await app.vault.modify(existing, content);
		return;
	}

	if (existing) {
		throw new Error(`Cannot write todo index: ${outputFile} is not a file.`);
	}

	await ensureParentFolder(app, outputFile);
	await app.vault.create(outputFile, content);
}

async function ensureParentFolder(app: App, filePath: string): Promise<void> {
	const parts = filePath.split('/');
	parts.pop();

	let currentPath = '';
	for (const part of parts) {
		currentPath = currentPath ? `${currentPath}/${part}` : part;
		const existing = app.vault.getAbstractFileByPath(currentPath);

		if (existing instanceof TFolder) {
			continue;
		}

		if (existing) {
			throw new Error(
				`Cannot create folder ${currentPath}: a file exists at that path.`,
			);
		}

		await app.vault.createFolder(currentPath);
	}
}

function normalizeScanFolders(scanFolders: string[]): string[] {
	const normalized = scanFolders.map(normalizeFolderPath).filter(Boolean);

	if (normalized.length === 0) {
		throw new Error('Set at least one folder to scan.');
	}

	return normalized;
}

function normalizeOutputFile(outputFile: string): string {
	const normalized = normalizePath(outputFile.trim()).replace(/^\/+/, '');

	if (!normalized) {
		throw new Error('Set an output file.');
	}

	if (!normalized.toLowerCase().endsWith('.md')) {
		throw new Error('Output file must end in .md.');
	}

	return normalized;
}

function normalizeFolderPath(folder: string): string {
	return normalizePath(folder.trim()).replace(/^\/+|\/+$/g, '');
}

function isInScanFolder(filePath: string, scanFolders: string[]): boolean {
	return scanFolders.some(
		(folder) => filePath === folder || filePath.startsWith(`${folder}/`),
	);
}
